name:

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  GCP_PROJECT: venimodellen
  REGION: europe-west4
  REGISTRY: europe-west4-docker.pkg.dev
  ARTIFACT_REPO: veni-modellen
  IMAGE_NAME: veni-modellen-applicatie
  CONTAINER_PORT: 8080
  SERVICE_ACCOUNT: basis-shiny-dashboard@timformatie.iam.gserviceaccount.com

jobs:
  build_and_push:
    name: Build image and push to registry
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        id: auth
        with:
          token_format: access_token
          workload_identity_provider: 'projects/1031676417138/locations/global/workloadIdentityPools/github-workload-pool/providers/github'
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.GCP_PROJECT }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}

      - name: Create and populate .Renviron file
        env:
          RENVIRON: ${{ secrets.RENVIRON }}
        run: |
          touch .Renviron
          echo "$RENVIRON" | base64 --decode > .Renviron

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          secrets: |
            GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}
          export_default_credentials: true

      - name: Substitute environment variables in YAML
        run: |
          cat inst/service.yml |
          sed 's/GCP_PROJECT_PLACEHOLDER/${{ env.GCP_PROJECT }}/g' |
          sed 's/REGION_PLACEHOLDER/${{ env.REGION }}/g' |
          sed 's/REGISTRY_PLACEHOLDER/${{ env.REGISTRY }}/g' |
          sed 's/ARTIFACT_REPO_PLACEHOLDER/${{ env.ARTIFACT_REPO }}/g' |
          sed 's/IMAGE_NAME_PLACEHOLDER/${{ env.IMAGE_NAME }}/g' |
          sed 's/CONTAINER_PORT_PLACEHOLDER/${{ env.CONTAINER_PORT }}/g' |
          sed 's/SERVICE_ACCOUNT_PLACEHOLDER/${{ env.SERVICE_ACCOUNT }}/g' > inst/service.yml

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          metadata: inst/service.yml
          region: ${{ env.REGION }}
